$id: 'https://spec.openapis.org/arazzo/1.0/schema/WORK-IN-PROGRESS'
$schema: 'https://json-schema.org/draft/2020-12/schema'

description: The description of OpenAPI Initiative Arazzo v1.0.x documents

type: object
