name: validate-markdown

# Author: @MikeRalphson
# Issue: https://github.com/OAI/OpenAPI-Specification/issues/2130

#
# This workflow validates markdown files in the project root.
# It also validates the work-in-progress specification file src/arazzo.md with slightly different rules.
#

# run this on push to any branch and creation of pull-requests
on: [push, pull_request]

jobs:
  mdv:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # checkout repo content
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4 # setup Node.js
      with:
        node-version: '20.x'

    - name: Lint work-in-progress spec
      run: npx --yes markdownlint-cli2 --config spec.markdownlint.yaml src/arazzo.md

    - name: Lint other files
      run: npx --yes markdownlint-cli2 *.md
